services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - /home/anda-cun/data/wordpress:/var/www/html
    restart: always
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - /home/anda-cun/data/mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wp_admin_password
    secrets:
       - db_password
       - wp_admin_password
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/anda-cun/data/wordpress:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_password
       - wp_admin_password
    restart: always
    networks:
      - inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    driver: bridge