name: inception

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/wp_admin_password
    secrets:
       - db_password
       - wp_admin_password
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
       - db_password
       - wp_admin_password
    restart: on-failure
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        USERNAME: ${USERNAME}
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    restart: on-failure
    environment:
      - USERNAME=${USERNAME}
    env_file:
      - .env
    networks:
      - inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

volumes:
  wp:
    driver_opts:
      type: none
      device: /home/$USERNAME/data/wordpress
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/$USERNAME/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge